# server port
server:
  port: 8083

# Vue.js 프론트엔드 정적 콘텐츠를 제공하기 위한 설정
spring:
  mvc:
    static-path-pattern: /**
  # data base
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_bulletinBoard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_bulletinBoard
    password: 1234

  # thymeleaf
  thymeleaf:
    cache: false

  # spring data jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
  web:
    resources:
      static-locations: classpath:/static/

# db query log
logging:
  level:
    org:
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace
